; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32532.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
COMM	iNo1:DWORD
_DATA	ENDS
PUBLIC	main
EXTRN	printf:PROC
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+127
	DD	imagerel $unwind$main
pdata	ENDS
_DATA	SEGMENT
$SG7547	DB	'%d%%%d = %d ', 0aH, 00H
	ORG $+2
$SG7548	DB	'%d%%%d = %d', 0aH, 00H
	ORG $+3
$SG7549	DB	'%d%%%d = %d', 0aH, 00H
	ORG $+3
$SG7550	DB	'%d%%%d = %d', 0aH, 00H
_DATA	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File D:\SOHAM\C\C_BATCH\8_modulus\8_modulus.c
; Line 4
$LN3:
	sub	rsp, 40					; 00000028H
; Line 5
	mov	r9d, 1
	mov	r8d, 2
	mov	edx, 9
	lea	rcx, OFFSET FLAT:$SG7547
	call	printf
; Line 7
	mov	r9d, 1
	mov	r8d, -2
	mov	edx, 9
	lea	rcx, OFFSET FLAT:$SG7548
	call	printf
; Line 9
	mov	r9d, -1
	mov	r8d, 2
	mov	edx, -9
	lea	rcx, OFFSET FLAT:$SG7549
	call	printf
; Line 11
	mov	r9d, -1
	mov	r8d, -2
	mov	edx, -9
	lea	rcx, OFFSET FLAT:$SG7550
	call	printf
; Line 13
	xor	eax, eax
; Line 14
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
END
